// Kundetyper (customer types / industries) collection. One node per industry;
// the hub is the "why we exist" / differentiation page. Copy bodies live in
// ./copy/*, metadata (routing/SEO/hierarchy) lives here.

import type { MarketingNode, MarketingHub } from "./types";
import {
  KUNDETYPER_HUB_COPY,
  KT_TOMRER,
  KT_MALER,
  KT_ELEKTRIKER,
  KT_VVS,
  KT_VVS_BODY,
  KT_ENTREPRENOER,
  KT_VOGNMAND,
} from "./copy/kundetyper-a";
import {
  KT_REVISOR,
  KT_PLASTFABRIKANT,
  KT_RAADGIVER,
  KT_KONSULENT,
  KT_FRISOER,
  KT_STORE,
} from "./copy/kundetyper-b";

export const KUNDETYPER_HUB: MarketingHub = {
  collection: "kundetyper",
  route: "/kundetyper",
  pageKey: "page.kundetyper",
  title: "Kundetyper",
  seoTitle: "Klimaregnskab for din branche | qlim8",
  seoDescription:
    "qlim8 bygger klimaregnskabet oven på dit regnskab, tilpasset din branche. Find din type virksomhed og se, hvordan vi løser lige præcis dine ESG-krav.",
  defaults: KUNDETYPER_HUB_COPY,
};

export const KUNDETYPER_NODES: MarketingNode[] = [
  {
    collection: "kundetyper",
    slug: "tomrer",
    pageKey: "page.kundetyper.tomrer",
    title: "Tømrer",
    navLabel: "Tømrer",
    blurb: "Klimaregnskab for tømrervirksomheden, fra varevogne til materialeindkøb.",
    seoTitle: "Klimaregnskab for tømrer | qlim8",
    seoDescription:
      "Tømrervirksomhed? Få klimaregnskab og ESG-rapport bygget på dit regnskab. Vi håndterer diesel, materialer og byggeprojekternes ESG-krav automatisk.",
    navGroup: "Brancher",
    featured: true,
    related: ["maler", "elektriker", "entreprenoer"],
    defaults: KT_TOMRER,
  },
  {
    collection: "kundetyper",
    slug: "maler",
    pageKey: "page.kundetyper.maler",
    title: "Maler",
    navLabel: "Maler",
    blurb: "Klimaregnskab for malerfirmaet: maling, kemi og dokumentation til bygherrer.",
    seoTitle: "Klimaregnskab for malerfirma | qlim8",
    seoDescription:
      "Malerfirma? Klimaregnskab og ESG-dokumentation bygget på dit regnskab. Vi håndterer maling, kemi og bygherrernes krav, uden regneark.",
    navGroup: "Brancher",
    featured: true,
    related: ["tomrer", "elektriker", "entreprenoer"],
    defaults: KT_MALER,
  },
  {
    collection: "kundetyper",
    slug: "elektriker",
    pageKey: "page.kundetyper.elektriker",
    title: "Elektriker",
    navLabel: "Elektrikere",
    blurb: "Klimaregnskab for el-installatøren: servicevogne, materialer og udbudskrav.",
    seoTitle: "Klimaregnskab for elektriker | qlim8",
    seoDescription:
      "El-installatør? Få klimaregnskab og ESG-data bygget på dit regnskab. Vi håndterer servicevogne, materialeindkøb og krav fra større byggeprojekter.",
    navGroup: "Brancher",
    featured: true,
    related: ["vvs", "tomrer", "entreprenoer"],
    defaults: KT_ELEKTRIKER,
  },
  {
    collection: "kundetyper",
    slug: "vvs",
    pageKey: "page.kundetyper.vvs",
    title: "VVS'ere",
    navLabel: "VVS'ere",
    blurb: "Klimaregnskab for VVS-firmaet: servicevogne, materialer, kølemidler og udbud.",
    seoTitle: "Klimaregnskab for VVS-firma | qlim8",
    seoDescription:
      "VVS-firma? Få et komplet klimaregnskab bygget på dit regnskab. Vi håndterer servicevogne, materialer, F-gasser og bygherrernes ESG-krav automatisk.",
    navGroup: "Brancher",
    featured: true,
    related: ["elektriker", "tomrer", "entreprenoer"],
    defaults: KT_VVS,
    body: KT_VVS_BODY,
  },
  {
    collection: "kundetyper",
    slug: "entreprenoer",
    pageKey: "page.kundetyper.entreprenoer",
    title: "Entreprenører",
    navLabel: "Entreprenører",
    blurb: "Klimaregnskab for entreprenøren: maskiner, materialer og offentlige udbud.",
    seoTitle: "Klimaregnskab for entreprenør | qlim8",
    seoDescription:
      "Entreprenørvirksomhed? Klimaregnskab og ESG-data til offentlige udbud, bygget på dit regnskab. Vi håndterer maskiner, beton, stål og underleverandører.",
    navGroup: "Brancher",
    featured: true,
    related: ["tomrer", "vvs", "store-virksomheder"],
    defaults: KT_ENTREPRENOER,
  },
  {
    collection: "kundetyper",
    slug: "revisor",
    pageKey: "page.kundetyper.revisor",
    title: "Revisorer",
    navLabel: "Revisorer",
    blurb: "Lever klimaregnskab til dine kunder, flere ESG-opgaver pr. fakturerbar time.",
    seoTitle: "Klimaregnskab for revisorer | qlim8",
    seoDescription:
      "Revisor? Lever klimaregnskab og VSME-rapporter til dine kunder på qlim8. Én platform, adgang på tværs af klienter og flere ESG-opgaver pr. time.",
    navGroup: "Rådgivere",
    featured: true,
    related: ["raadgiver", "konsulent", "store-virksomheder"],
    defaults: KT_REVISOR,
  },
  {
    collection: "kundetyper",
    slug: "plastfabrikant",
    pageKey: "page.kundetyper.plastfabrikant",
    title: "Plastik fabrikanter",
    navLabel: "Plastik fabrikanter",
    blurb: "Klimaregnskab for plastproduktion: energi, råvarer og kunders PCF-krav.",
    seoTitle: "Klimaregnskab for plastproduktion | qlim8",
    seoDescription:
      "Plastfabrikant? Klimaregnskab bygget på dit regnskab og elforbrug. Vi håndterer energi, granulat og kundernes krav om produkt-CO₂e (PCF).",
    navGroup: "Brancher",
    featured: true,
    related: ["store-virksomheder", "entreprenoer", "raadgiver"],
    defaults: KT_PLASTFABRIKANT,
  },
  {
    collection: "kundetyper",
    slug: "raadgiver",
    pageKey: "page.kundetyper.raadgiver",
    title: "Rådgivere",
    navLabel: "Rådgivere",
    blurb: "Rådgiv dine kunder på klima og ESG med data i stedet for regneark.",
    seoTitle: "Klima- og ESG-rådgivning på data | qlim8",
    seoDescription:
      "Rådgiver? Lever datadrevet klima- og ESG-rådgivning til dine kunder på qlim8. Skalér rådgivningen med adgang på tværs af klienter.",
    navGroup: "Rådgivere",
    featured: true,
    related: ["revisor", "konsulent", "store-virksomheder"],
    defaults: KT_RAADGIVER,
  },
  {
    collection: "kundetyper",
    slug: "konsulent",
    pageKey: "page.kundetyper.konsulent",
    title: "Konsulenter",
    navLabel: "Konsulenter",
    blurb: "Lever målbare klimaregnskaber og reduktionsplaner til flere kunder.",
    seoTitle: "Klimaregnskab for konsulenter | qlim8",
    seoDescription:
      "Bæredygtighedskonsulent? Lever målbare klimaregnskaber, tiltag og scenarier til dine kunder på qlim8, effektivt og med audit-spor.",
    navGroup: "Rådgivere",
    featured: true,
    related: ["raadgiver", "revisor", "store-virksomheder"],
    defaults: KT_KONSULENT,
  },
  {
    collection: "kundetyper",
    slug: "vognmand",
    pageKey: "page.kundetyper.vognmand",
    title: "Vognmand",
    navLabel: "Vognmand",
    blurb: "Klimaregnskab for transport: brændstof, flåde og kundernes Scope 3-krav.",
    seoTitle: "Klimaregnskab for vognmand | qlim8",
    seoDescription:
      "Vognmand eller transportvirksomhed? Klimaregnskab bygget på dit regnskab. Vi håndterer brændstof og leverer transport-emissionsdata til dine kunder.",
    navGroup: "Brancher",
    featured: true,
    related: ["entreprenoer", "store-virksomheder", "tomrer"],
    defaults: KT_VOGNMAND,
  },
  {
    collection: "kundetyper",
    slug: "frisoer",
    pageKey: "page.kundetyper.frisoer",
    title: "Frisør",
    navLabel: "Frisør",
    blurb: "Klimaregnskab for salonen: klaret på en eftermiddag, klar til bank og kæde.",
    seoTitle: "Klimaregnskab for frisørsalon | qlim8",
    seoDescription:
      "Frisørsalon? Få et enkelt klimaregnskab bygget på dit regnskab og elforbrug: klar-til-brug, når bank, leverandør eller kæde spørger.",
    navGroup: "Brancher",
    featured: true,
    related: ["vognmand", "maler", "store-virksomheder"],
    defaults: KT_FRISOER,
  },
  {
    collection: "kundetyper",
    slug: "store-virksomheder",
    pageKey: "page.kundetyper.store-virksomheder",
    title: "Store virksomheder",
    navLabel: "Store virksomheder",
    blurb: "CSRD og Scope 3 i værdikæden: aggregér data fra dine leverandører.",
    seoTitle: "Klimaregnskab og CSRD for store virksomheder | qlim8",
    seoDescription:
      "Større virksomhed med CSRD-krav? Aggregér Scope 3 fra dine leverandører, send ét link og få audit-spor. Bygget på dit regnskab.",
    navGroup: "Brancher",
    featured: true,
    related: ["entreprenoer", "plastfabrikant", "revisor"],
    defaults: KT_STORE,
  },
];
