// Produkt (features) collection. Flat URLs; hierarchy is expressed via
// parentSlug (breadcrumbs + in-page sub-nav) and navGroup (mega-menu column).
// `featured` marks the top-level areas shown as cards on the hub.

import type { MarketingNode, MarketingHub } from "./types";
import {
  PRODUKT_HUB_COPY,
  PR_DASHBOARD,
  PR_UDFORSKNING,
  PR_DATA_UDTRAEK,
  PR_RAPPORTERING,
  PR_EXCEL,
  PR_PDF,
  PR_AUDIT,
} from "./copy/produkt-a";
import {
  PR_MODTAGERE,
  PR_BESTYRELSE,
  PR_INVESTOR,
  PR_BANK,
  PR_SAMARBEJDSPARTNERE,
  PR_TEMAER,
  PR_VSME,
  PR_VSME_BASIS,
  PR_VSME_COMPREHENSIVE,
} from "./copy/produkt-b";
import {
  PR_TILTAG,
  PR_SCENARIER,
  PR_REVISOR_ADGANG,
  PR_LEVERANDOERKAEDE,
  PR_BRAGBOARD,
} from "./copy/produkt-c";

export const PRODUKT_HUB: MarketingHub = {
  collection: "produkt",
  route: "/produkt",
  pageKey: "page.produkt",
  title: "Produkt",
  seoTitle: "Produkt: klimaregnskab fra data til rapport | qlim8",
  seoDescription:
    "Se hele qlim8-platformen: dashboard, udforskning, rapportering, tiltag, scenarier, revisor-adgang og leverandørkæde. Klimaregnskabet bygget på dit regnskab.",
  defaults: PRODUKT_HUB_COPY,
};

export const PRODUKT_NODES: MarketingNode[] = [
  // --- Overblik ---
  {
    collection: "produkt", slug: "dashboard", pageKey: "page.produkt.dashboard",
    title: "Dashboard", navLabel: "Dashboard",
    blurb: "Samlet overblik over dit klimaregnskab: scopes, kategorier og udvikling.",
    seoTitle: "Klimaregnskab-dashboard | qlim8",
    seoDescription: "Ét dashboard med hele dit klimaregnskab: scope 1-3, kategorier, udvikling over tid og status mod dine mål. Uden regneark.",
    navGroup: "Overblik", featured: true, related: ["udforskning", "rapportering", "tiltag"],
    defaults: PR_DASHBOARD,
  },
  {
    collection: "produkt", slug: "udforskning", pageKey: "page.produkt.udforskning",
    title: "Udforskning", navLabel: "Udforskning",
    blurb: "Dyk ned i data bag tallene: filtrér på scope, kategori, afdeling og leverandør.",
    seoTitle: "Udforsk dit klimaregnskab | qlim8",
    seoDescription: "Find ud af, hvor emissionerne kommer fra. Filtrér på scope, kategori, afdeling, leverandør og periode, helt ned til det enkelte bilag.",
    navGroup: "Overblik", featured: true, related: ["data-udtraek", "dashboard", "leverandoerkaede"],
    defaults: PR_UDFORSKNING,
  },
  {
    collection: "produkt", slug: "data-udtraek", pageKey: "page.produkt.data-udtraek",
    title: "Data udtræk", navLabel: "Data udtræk",
    blurb: "Træk rå- og aggregerede data ud med fuld sporbarhed tilbage til bilaget.",
    seoTitle: "Data udtræk og eksport | qlim8",
    seoDescription: "Eksportér rå og aggregerede klimadata til egne analyser eller din revisor, med emission-lineage hele vejen tilbage til posteringen.",
    parentSlug: "udforskning", navGroup: "Overblik", related: ["udforskning", "excel-rapport", "audit-trail"],
    defaults: PR_DATA_UDTRAEK,
  },
  // --- Rapportering ---
  {
    collection: "produkt", slug: "rapportering", pageKey: "page.produkt.rapportering",
    title: "Rapportering", navLabel: "Rapportering",
    blurb: "Fra data til færdig rapport: Excel, PDF, VSME og audit trail.",
    seoTitle: "ESG- og klimarapportering | qlim8",
    seoDescription: "Færdig klimarapport direkte fra platformen: Excel, underskrifts-klar PDF, VSME Basic/Comprehensive og fuldt audit-spor. Klar til revisor og bank.",
    navGroup: "Rapportering", featured: true, related: ["pdf-rapport", "vsme-rapport", "audit-trail"],
    defaults: PR_RAPPORTERING,
  },
  {
    collection: "produkt", slug: "excel-rapport", pageKey: "page.produkt.excel-rapport",
    title: "Excel rapport", navLabel: "Excel rapport",
    blurb: "Struktureret Excel-eksport til revisor, hvert tal med kildehenvisning.",
    seoTitle: "Klimaregnskab som Excel-rapport | qlim8",
    seoDescription: "Eksportér klimaregnskabet til en struktureret Excel-rapport til revisor og videre bearbejdning, med kildehenvisning på hvert tal.",
    parentSlug: "rapportering", navGroup: "Rapportering", related: ["pdf-rapport", "data-udtraek", "audit-trail"],
    defaults: PR_EXCEL,
  },
  {
    collection: "produkt", slug: "pdf-rapport", pageKey: "page.produkt.pdf-rapport",
    title: "PDF rapport", navLabel: "PDF rapport",
    blurb: "Underskrifts-klar PDF, med temaer og tilpasset modtageren.",
    seoTitle: "Klimaregnskab som PDF-rapport | qlim8",
    seoDescription: "Underskrifts-klar PDF-rapport med valgfrit tema (Light Nordic / McKinsey), tilpasset modtageren: bestyrelse, investor, bank eller samarbejdspartner.",
    parentSlug: "rapportering", navGroup: "Rapportering", related: ["temaer", "modtagere", "excel-rapport"],
    defaults: PR_PDF,
  },
  {
    collection: "produkt", slug: "modtagere", pageKey: "page.produkt.modtagere",
    title: "Modtagere", navLabel: "Modtagere",
    blurb: "Samme regnskab, tilpasset hvem der læser: bestyrelse, investor, bank, partner.",
    seoTitle: "Rapport tilpasset modtageren | qlim8",
    seoDescription: "Tilpas klimarapporten til modtageren: bestyrelse, investorer, bank eller samarbejdspartnere. Samme data: rette detaljeringsgrad til rette læser.",
    parentSlug: "pdf-rapport", navGroup: "Rapportering", related: ["bestyrelsesrapport", "bankrapport", "investorrapport"],
    defaults: PR_MODTAGERE,
  },
  {
    collection: "produkt", slug: "bestyrelsesrapport", pageKey: "page.produkt.bestyrelsesrapport",
    title: "Bestyrelsesrapport", navLabel: "Bestyrelse",
    blurb: "Beslutningsklart klimaregnskab til bestyrelsen: mål, afvigelse og risiko.",
    seoTitle: "Klimaregnskab til bestyrelsen | qlim8",
    seoDescription: "Giv bestyrelsen et beslutningsklart klimaregnskab: status mod mål, afvigelser og risici, på få sider, uden regneark.",
    parentSlug: "modtagere", navGroup: "Rapportering", related: ["investorrapport", "bankrapport", "modtagere"],
    defaults: PR_BESTYRELSE,
  },
  {
    collection: "produkt", slug: "investorrapport", pageKey: "page.produkt.investorrapport",
    title: "Investorrapport", navLabel: "Investorer",
    blurb: "ESG-data til investorer og ejere: sammenlignelig og GHG Protocol-konsistent.",
    seoTitle: "ESG-rapport til investorer | qlim8",
    seoDescription: "Lever ESG- og klimadata til investorer og ejere: sammenlignelige tal, GHG Protocol-konsistens og udvikling over tid.",
    parentSlug: "modtagere", navGroup: "Rapportering", related: ["bestyrelsesrapport", "bankrapport", "modtagere"],
    defaults: PR_INVESTOR,
  },
  {
    collection: "produkt", slug: "bankrapport", pageKey: "page.produkt.bankrapport",
    title: "Bankrapport", navLabel: "Bank",
    blurb: "Opfyld bankens ESG-datakrav til finansiering, klar-til-upload.",
    seoTitle: "ESG-rapport til banken | qlim8",
    seoDescription: "Opfyld bankens ESG- og L193-datakrav til finansiering med en klar-til-upload klimarapport, bygget på dit regnskab.",
    parentSlug: "modtagere", navGroup: "Rapportering", related: ["bestyrelsesrapport", "investorrapport", "modtagere"],
    defaults: PR_BANK,
  },
  {
    collection: "produkt", slug: "samarbejdspartnere", pageKey: "page.produkt.samarbejdspartnere",
    title: "Samarbejdspartnere", navLabel: "Samarbejdspartnere",
    blurb: "Del klimadata med kunder og leverandører, ét link i stedet for regneark.",
    seoTitle: "Del klimadata med samarbejdspartnere | qlim8",
    seoDescription: "Del dit klimaregnskab med kunder og leverandører, der beder om data til deres Scope 3, via ét link i stedet for regneark på mail.",
    parentSlug: "modtagere", navGroup: "Rapportering", related: ["leverandoerkaede", "brag-board", "modtagere"],
    defaults: PR_SAMARBEJDSPARTNERE,
  },
  {
    collection: "produkt", slug: "temaer", pageKey: "page.produkt.temaer",
    title: "Temaer", navLabel: "Temaer",
    blurb: "Vælg rapportens visuelle tema: Light Nordic eller McKinsey.",
    seoTitle: "Rapport-temaer: Light Nordic & McKinsey | qlim8",
    seoDescription: "Vælg det visuelle tema til din PDF-rapport: rene, nordiske Light Nordic eller stringente McKinsey. Samme data: to udtryk.",
    parentSlug: "pdf-rapport", navGroup: "Rapportering", related: ["pdf-rapport", "modtagere", "rapportering"],
    defaults: PR_TEMAER,
  },
  {
    collection: "produkt", slug: "vsme-rapport", pageKey: "page.produkt.vsme-rapport",
    title: "VSME rapport", navLabel: "VSME rapport",
    blurb: "Den frivillige VSME-standard for SMV'er, Basic og Comprehensive.",
    seoTitle: "VSME-rapport for SMV'er | qlim8",
    seoDescription: "Rapportér efter VSME: den frivillige bæredygtighedsstandard for SMV'er. qlim8 laver både VSME Basic og VSME Comprehensive direkte fra dine data.",
    parentSlug: "rapportering", navGroup: "Rapportering", related: ["vsme-basis", "vsme-comprehensive", "rapportering"],
    defaults: PR_VSME,
  },
  {
    collection: "produkt", slug: "vsme-basis", pageKey: "page.produkt.vsme-basis",
    title: "VSME Basic", navLabel: "VSME Basic",
    blurb: "VSME Basic-modulet: kom hurtigt i mål med det grundlæggende.",
    seoTitle: "VSME Basic | qlim8",
    seoDescription: "VSME Basic dækker de grundlæggende datapunkter. Se hvem modulet passer til, og hvor hurtigt du er i mål med dit regnskab som kilde.",
    parentSlug: "vsme-rapport", navGroup: "Rapportering", related: ["vsme-comprehensive", "vsme-rapport", "rapportering"],
    defaults: PR_VSME_BASIS,
  },
  {
    collection: "produkt", slug: "vsme-comprehensive", pageKey: "page.produkt.vsme-comprehensive",
    title: "VSME Comprehensive", navLabel: "VSME Comprehensive",
    blurb: "Det udvidede VSME-modul: flere datapunkter, Scope 3 og politikker.",
    seoTitle: "VSME Comprehensive | qlim8",
    seoDescription: "VSME Comprehensive dækker flere datapunkter, Scope 3 og politikker/mål, til dig der har krav fra bank eller store kunder.",
    parentSlug: "vsme-rapport", navGroup: "Rapportering", related: ["vsme-basis", "vsme-rapport", "leverandoerkaede"],
    defaults: PR_VSME_COMPREHENSIVE,
  },
  {
    collection: "produkt", slug: "audit-trail", pageKey: "page.produkt.audit-trail",
    title: "Audit Trail", navLabel: "Audit Trail",
    blurb: "Hver kategori-ændring, faktor og datakilde logges automatisk.",
    seoTitle: "Audit trail til klimaregnskab | qlim8",
    seoDescription: "Fuldt revisor-klart spor: hver kategori-ændring, emissionsfaktor og datakilde logges automatisk, hvem ændrede hvad hvornår.",
    parentSlug: "rapportering", navGroup: "Rapportering", related: ["rapportering", "revisor-adgang", "data-udtraek"],
    defaults: PR_AUDIT,
  },
  // --- Handling ---
  {
    collection: "produkt", slug: "tiltag", pageKey: "page.produkt.tiltag",
    title: "Tiltag", navLabel: "Tiltag",
    blurb: "Opret og spor reduktionstiltag: se ROI og effekt på klimaregnskabet.",
    seoTitle: "Reduktionstiltag og ROI | qlim8",
    seoDescription: "Opret reduktionstiltag, spor deres effekt på klimaregnskabet og se ROI pr. tiltag. Gør klimaregnskabet til et arbejdsredskab hele året.",
    navGroup: "Handling", featured: true, related: ["scenarier", "dashboard", "brag-board"],
    defaults: PR_TILTAG,
  },
  {
    collection: "produkt", slug: "scenarier", pageKey: "page.produkt.scenarier",
    title: "Scenarier", navLabel: "Scenarier",
    blurb: "Simulér fremtidige reduktionsstier og sammenlign mod dine mål.",
    seoTitle: "Scenarie-planlægger for klima | qlim8",
    seoDescription: "Simulér 'hvad nu hvis'-scenarier for dine reduktioner, sammenlign dem mod dine mål, og træf beslutninger på data i stedet for mavefornemmelse.",
    navGroup: "Handling", featured: true, related: ["tiltag", "dashboard", "leverandoerkaede"],
    defaults: PR_SCENARIER,
  },
  // --- Samarbejde ---
  {
    collection: "produkt", slug: "revisor-adgang", pageKey: "page.produkt.revisor-adgang",
    title: "Revisor adgang", navLabel: "Revisor adgang",
    blurb: "Giv revisor direkte adgang: færre frem-og-tilbage-mails.",
    seoTitle: "Revisor-adgang til klimaregnskab | qlim8",
    seoDescription: "Giv din revisor eller rådgiver direkte adgang til klimaregnskabet, så de kan validere data og audit-spor, uden endeløse mails.",
    navGroup: "Samarbejde", featured: true, related: ["audit-trail", "rapportering", "leverandoerkaede"],
    defaults: PR_REVISOR_ADGANG,
  },
  {
    collection: "produkt", slug: "leverandoerkaede", pageKey: "page.produkt.leverandoerkaede",
    title: "Leverandørkæde", navLabel: "Leverandørkæde",
    blurb: "Kortlæg leverandører via CVR og indsaml deres Scope 3-data med ét link.",
    seoTitle: "Leverandørkæde og Scope 3 | qlim8",
    seoDescription: "Kortlæg din leverandørkæde via CVR-opslag, send ét link og få leverandørernes Scope 3-data. Se dækningsgrad og eksponering.",
    navGroup: "Samarbejde", featured: true, related: ["scenarier", "samarbejdspartnere", "store-virksomheder"],
    defaults: PR_LEVERANDOERKAEDE,
  },
  {
    collection: "produkt", slug: "brag-board", pageKey: "page.produkt.brag-board",
    title: "Brag Board", navLabel: "Brag Board",
    blurb: "Offentlig ESG-profil: brug klimaregnskabet som salgsargument.",
    seoTitle: "Brag Board: offentlig ESG-profil | qlim8",
    seoDescription: "Del en offentlig ESG-profil (Brag Board) og brug dit klimaregnskab som salgsargument i udbud og kundedialog.",
    navGroup: "Samarbejde", featured: true, related: ["tiltag", "samarbejdspartnere", "dashboard"],
    defaults: PR_BRAGBOARD,
  },
];
